apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/nmasse-itix/rhacs-gitops.git
    targetRevision: main
    path: charts/rhacs
    helm:
      parameters:
      - name: masterKey
        value: "S3cr3t!"
      - name: openshiftDnsZone
        value: apps.ocp.tld
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
